version: '3'

services:

    php:
        image: php:7.3.3-apache
        ports:
            - 8080:80
        volumes: 
            - ./public:/var/www/html/
        networks:
            default:
                ipv4_address: 172.28.1.1

    mercure:
        image: dunglas/mercure:v0.4.1
        ports:
            - 3000:3000
        environment: 
            - JWT_KEY=myVerySecretKey
            - ADDR=:3000
            - PUBLISH_ALLOWED_ORIGINS=http://localhost:3000
            - ALLOW_ANONYMOUS=1
            - CORS_ALLOWED_ORIGINS=*
        networks:
            default:
                ipv4_address: 172.28.1.2

networks:
    default:
        ipam:
            config:
                - subnet: 172.28.0.0/16
